
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "github.com/imdario/mergo"
  branch = "master"

[[override]]
  name = "k8s.io/gengo"
  revision = "b90029ef6cd877cb3f422d75b3a07707e3aac6b7"
